version: "3.9"
services:
  frontend:
    build: .
    command: npm run dev
    working_dir: /app
    ports:
      - "5173:5173" # Vite default
      - "8080:8080"
    volumes:
      - .:/app
      - /Media:/Media
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    restart: unless-stopped
  backend:
    build: .
    command: node server.js
    working_dir: /app/server
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /Media:/Media
    environment:
      - NODE_ENV=development
    restart: unless-stopped
